repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.4.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [fix, feat, docs, style, refactor, perf, test, build, ci, chore, revert, merge]
      fail_fast: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        language_version: python3.10
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.289
  hooks:
    - id: ruff
      name: ruff
